package main

// Integration tests for the wrapper `dw init` prints. They build the real
// binary, put it on PATH next to a stub fzf, and run __dw_pick under both
// shells — so the picker's control flow (which exit status means "create",
// when the loop re-enters, when nothing must be created) is covered without
// needing a terminal.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// stubFzf stands in for fzf. It records its arguments and stdin, then replays
// the canned answer for this invocation: STUB_OUT<n> on stdout, STUB_ST<n> as
// the exit status. Numbering the answers is what lets a test assert that the
// picker loop re-enters exactly once and then settles.
const stubFzf = `#!/bin/sh
n=$(( $(cat "$STUB_DIR/calls" 2>/dev/null || echo 0) + 1 ))
echo "$n" > "$STUB_DIR/calls"
printf '%s\n' "$*" >> "$STUB_DIR/args"
cat > "$STUB_DIR/stdin.$n"
eval "out=\$STUB_OUT$n"
eval "st=\$STUB_ST$n"
[ -n "$out" ] && printf '%s\n' "$out"
exit "${st:-0}"
`

// shellEnv is one isolated run of the wrapper: a DW_ROOT to create workspaces
// in, a bin dir holding the real dw plus the stub fzf, and the stub's scratch
// space.
type shellEnv struct {
	root    string
	binDir  string
	stubDir string
}

// buildEnv compiles dw into a temp bin dir and installs the stub fzf beside
// it. The binary is built once per test via t.TempDir so runs cannot see each
// other's workspaces.
func buildEnv(t *testing.T) shellEnv {
	t.Helper()
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not on PATH")
	}
	base := t.TempDir()
	env := shellEnv{
		root:    filepath.Join(base, "root"),
		binDir:  filepath.Join(base, "bin"),
		stubDir: filepath.Join(base, "stub"),
	}
	for _, d := range []string{env.root, env.binDir, env.stubDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	build := exec.Command("go", "build", "-o", filepath.Join(env.binDir, "dw"), ".")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build: %v\n%s", err, out)
	}
	if err := os.WriteFile(filepath.Join(env.binDir, "fzf"), []byte(stubFzf), 0o755); err != nil { //nolint:gosec // a stub executable has to be executable
		t.Fatal(err)
	}
	return env
}

// wrapperFor returns the shell function text, generated by the binary under
// test rather than read off the constant, so the test exercises what users
// actually eval.
func (e shellEnv) wrapperFor(t *testing.T, shell string) string {
	t.Helper()
	out, err := exec.Command(filepath.Join(e.binDir, "dw"), "init", shell).Output()
	if err != nil {
		t.Fatalf("dw init %s: %v", shell, err)
	}
	return string(out)
}

// run evaluates the wrapper in shell and executes script. Both shells are
// started with startup files disabled: a user's ~/.zshenv is read even by
// `zsh -c`, and one that re-prepends /opt/homebrew/bin silently replaces the
// stub fzf with the real one, which then hangs waiting for a terminal. The
// helper asserts the stub won resolution before running anything.
func (e shellEnv) run(t *testing.T, shell, script string, extraEnv ...string) (stdout, stderr string, code int) {
	t.Helper()
	bin, err := exec.LookPath(shell)
	if err != nil {
		t.Skipf("%s not installed", shell)
	}
	flags := []string{"-f", "-c"}
	if shell == "bash" {
		flags = []string{"--noprofile", "--norc", "-c"}
	}
	guard := `case "$(command -v fzf)" in
  "$STUB_BIN") : ;;
  *) echo "stub fzf shadowed by $(command -v fzf)" >&2; exit 99 ;;
esac
`
	cmd := exec.Command(bin, append(flags, e.wrapperFor(t, shell)+guard+script)...) //nolint:gosec // shell and script are test-controlled
	cmd.Env = append(os.Environ(),
		"PATH="+e.binDir+string(os.PathListSeparator)+os.Getenv("PATH"),
		"STUB_BIN="+filepath.Join(e.binDir, "fzf"),
		"STUB_DIR="+e.stubDir,
		"DW_ROOT="+e.root,
		"HOME="+filepath.Dir(e.root),
		"XDG_CACHE_HOME="+filepath.Join(filepath.Dir(e.root), "cache"),
	)
	cmd.Env = append(cmd.Env, extraEnv...)
	var out, errBuf strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errBuf
	if err := cmd.Run(); err != nil {
		var ee *exec.ExitError
		if !asExitError(err, &ee) {
			t.Fatalf("%s: %v (stderr: %s)", shell, err, errBuf.String())
		}
		code = ee.ExitCode()
	}
	if code == 99 {
		t.Fatalf("PATH isolation failed: %s", errBuf.String())
	}
	return out.String(), errBuf.String(), code
}

func asExitError(err error, target **exec.ExitError) bool {
	ee, ok := err.(*exec.ExitError)
	if ok {
		*target = ee
	}
	return ok
}

// mkWorkspace creates <root>/<name>/ so a test starts with existing rows.
func (e shellEnv) mkWorkspace(t *testing.T, name string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Join(e.root, name), 0o755); err != nil {
		t.Fatal(err)
	}
}

// dirs lists the workspace directories currently under root.
func (e shellEnv) dirs(t *testing.T) []string {
	t.Helper()
	entries, err := os.ReadDir(e.root)
	if err != nil {
		t.Fatal(err)
	}
	var out []string
	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), ".") {
			out = append(out, entry.Name())
		}
	}
	return out
}

// fzfCalls reports how many times the stub was invoked.
func (e shellEnv) fzfCalls(t *testing.T) int {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(e.stubDir, "calls"))
	if err != nil {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(b)))
	if err != nil {
		t.Fatal(err)
	}
	return n
}

// answer builds the STUB_OUT<n>/STUB_ST<n> pair for one fzf invocation.
func answer(n int, out string, status int) []string {
	return []string{
		fmt.Sprintf("STUB_OUT%d=%s", n, out),
		fmt.Sprintf("STUB_ST%d=%d", n, status),
	}
}

// selection is what fzf prints with --print-query when the user picks a row:
// the query, then the chosen line.
func selection(query, row string) string { return query + "\n" + row }

func eachShell(t *testing.T, fn func(t *testing.T, shell string)) {
	t.Helper()
	for _, shell := range []string{"bash", "zsh"} {
		t.Run(shell, func(t *testing.T) { fn(t, shell) })
	}
}

// TestPick_EmptyRootCreatesTypedTopic is the first-run path: no workspaces at
// all, so fzf shows an empty list, and whatever is typed becomes the topic.
func TestPick_EmptyRootCreatesTypedTopic(t *testing.T) {
	eachShell(t, func(t *testing.T, shell string) {
		env := buildEnv(t)
		stdout, stderr, code := env.run(t, shell, "__dw_pick", answer(1, "first topic", 1)...)
		if code != 0 {
			t.Fatalf("code = %d, want 0 (stderr: %s)", code, stderr)
		}
		dirs := env.dirs(t)
		if len(dirs) != 1 || !strings.HasSuffix(dirs[0], "-first-topic") {
			t.Fatalf("root holds %v, want one <date>-first-topic workspace", dirs)
		}
		if !strings.Contains(stdout, dirs[0]) {
			t.Errorf("__dw_pick printed %q, want the row for %q", stdout, dirs[0])
		}
	})
}

// TestPick_EmptyRootFeedsFzfZeroItems guards the printf '%s' in the wrapper:
// with '%s\n' an empty list would reach fzf as one blank line, i.e. a
// selectable row that resolves to nothing.
func TestPick_EmptyRootFeedsFzfZeroItems(t *testing.T) {
	env := buildEnv(t)
	env.run(t, "bash", "__dw_pick", answer(1, "topic", 1)...)
	b, err := os.ReadFile(filepath.Join(env.stubDir, "stdin.1"))
	if err != nil {
		t.Fatal(err)
	}
	if len(b) != 0 {
		t.Errorf("fzf received %q, want zero bytes for an empty workspace list", b)
	}
}

// TestPick_SelectionOpensWithoutCreating covers the ordinary hit: one existing
// workspace, chosen from the picker.
func TestPick_SelectionOpensWithoutCreating(t *testing.T) {
	eachShell(t, func(t *testing.T, shell string) {
		env := buildEnv(t)
		env.mkWorkspace(t, "2026-01-01-alpha")
		row := filepath.Join(env.root, "2026-01-01-alpha") + "\t  alpha\t\t2026-01-01-alpha"

		stdout, stderr, code := env.run(t, shell, "__dw_pick", answer(1, selection("al", row), 0)...)
		if code != 0 {
			t.Fatalf("code = %d, want 0 (stderr: %s)", code, stderr)
		}
		if strings.TrimSpace(stdout) != row {
			t.Errorf("__dw_pick printed %q, want the selected row %q", stdout, row)
		}
		if dirs := env.dirs(t); len(dirs) != 1 {
			t.Errorf("root holds %v, want the single pre-existing workspace", dirs)
		}
	})
}

// TestPick_NoFzfMatchStillResolvesBySlug is the case that keeps the picker
// from manufacturing duplicates: fzf found nothing, but dw's own substring
// match on the slug does, so the existing workspace wins over creating one.
func TestPick_NoFzfMatchStillResolvesBySlug(t *testing.T) {
	eachShell(t, func(t *testing.T, shell string) {
		env := buildEnv(t)
		env.mkWorkspace(t, "2026-01-01-datadog-cost")

		stdout, stderr, code := env.run(t, shell, "__dw_pick", answer(1, "cost", 1)...)
		if code != 0 {
			t.Fatalf("code = %d, want 0 (stderr: %s)", code, stderr)
		}
		if dirs := env.dirs(t); len(dirs) != 1 {
			t.Fatalf("root holds %v, want no second workspace for a query that already matches", dirs)
		}
		if !strings.Contains(stdout, "2026-01-01-datadog-cost") {
			t.Errorf("__dw_pick printed %q, want the existing datadog-cost row", stdout)
		}
	})
}

// TestPick_AbortCreatesNothing covers ESC/ctrl-c (130) and enter on an empty
// query — neither may leave a directory behind.
func TestPick_AbortCreatesNothing(t *testing.T) {
	for _, tc := range []struct {
		name   string
		out    string
		status int
	}{
		{"escape", "typo", 130},
		{"empty query", "", 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			eachShell(t, func(t *testing.T, shell string) {
				env := buildEnv(t)
				env.mkWorkspace(t, "2026-01-01-alpha")

				stdout, _, code := env.run(t, shell, "__dw_pick", answer(1, tc.out, tc.status)...)
				if code == 0 {
					t.Errorf("code = 0, want non-zero so dw() skips the cd")
				}
				if strings.TrimSpace(stdout) != "" {
					t.Errorf("__dw_pick printed %q, want nothing", stdout)
				}
				if dirs := env.dirs(t); len(dirs) != 1 {
					t.Errorf("root holds %v, want only the pre-existing workspace", dirs)
				}
			})
		})
	}
}

// TestPick_SeveralSlugMatchesReenterOnce is the loop's termination guarantee.
// The query matches two workspaces by slug but neither by title, so the picker
// re-opens on just those two — with the query cleared, because re-opening on a
// query fzf already failed to match would spin forever.
func TestPick_SeveralSlugMatchesReenterOnce(t *testing.T) {
	eachShell(t, func(t *testing.T, shell string) {
		env := buildEnv(t)
		env.mkWorkspace(t, "2026-01-01-datadog-cost")
		env.mkWorkspace(t, "2026-01-02-datadog-alerts")
		chosen := filepath.Join(env.root, "2026-01-02-datadog-alerts") + "\t  datadog-alerts\t\t2026-01-02-datadog-alerts"

		env.run(t, shell, "__dw_pick",
			append(answer(1, "Datadog", 1), answer(2, selection("", chosen), 0)...)...)

		if got := env.fzfCalls(t); got != 2 {
			t.Errorf("fzf ran %d times, want exactly 2 (one re-entry, then settle)", got)
		}
		if dirs := env.dirs(t); len(dirs) != 2 {
			t.Errorf("root holds %v, want the two pre-existing workspaces", dirs)
		}
		args, err := os.ReadFile(filepath.Join(env.stubDir, "args"))
		if err != nil {
			t.Fatal(err)
		}
		second := strings.Split(strings.TrimRight(string(args), "\n"), "\n")[1]
		if !strings.Contains(second, "--query= ") {
			t.Errorf("second fzf call got %q, want an empty --query= so the loop can settle", second)
		}
	})
}

// TestPick_PassesArgumentsAsQuery checks that `dw <topic>` opens the picker
// pre-filled instead of resolving behind the user's back, and that the wrapper
// asks for the query back.
func TestPick_PassesArgumentsAsQuery(t *testing.T) {
	env := buildEnv(t)
	env.mkWorkspace(t, "2026-01-01-alpha")
	row := filepath.Join(env.root, "2026-01-01-alpha") + "\t  alpha\t\t2026-01-01-alpha"

	env.run(t, "bash", `__dw_pick "k8s" "mig"`, answer(1, selection("k8s mig", row), 0)...)

	args, err := os.ReadFile(filepath.Join(env.stubDir, "args"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(args)
	if !strings.Contains(got, "--print-query") {
		t.Errorf("fzf args %q lack --print-query, so a typed-but-unmatched topic could never be created", got)
	}
	if !strings.Contains(got, "--query=k8s mig") {
		t.Errorf("fzf args %q lack --query=k8s mig", got)
	}
}

// TestShellInit_ParsesInBothShells is the cheap backstop: the wrapper is a Go
// string constant, so nothing else would catch a syntax error in it.
func TestShellInit_ParsesInBothShells(t *testing.T) {
	env := buildEnv(t)
	for _, shell := range []string{"bash", "zsh"} {
		t.Run(shell, func(t *testing.T) {
			bin, err := exec.LookPath(shell)
			if err != nil {
				t.Skipf("%s not installed", shell)
			}
			script := filepath.Join(t.TempDir(), "wrapper.sh")
			if err := os.WriteFile(script, []byte(env.wrapperFor(t, shell)), 0o600); err != nil {
				t.Fatal(err)
			}
			if out, err := exec.Command(bin, "-n", script).CombinedOutput(); err != nil {
				t.Errorf("%s -n rejected the wrapper: %v\n%s", shell, err, out)
			}
		})
	}
}
